export const leadership = [
    {
        name: 'Vidya Ganga',
        img:  null,
        role: 'President',
        year: 'Junior',
        email: 'sreevidyaganga0@berkeley.edu',
        committee: null,
        project: null,
        tree: 'Karthick',
        leaf: 'Larissa',
        linkedin: 'https://www.linkedin.com/in/sreevidya-ganga-70113076/',
        resume: null,
        website: null,
        blurb: 'hi i <3 oatmeal and warm hugs ',
    },
    {
        name: 'Ethan Chen',
        img:  null,
        role: 'Vice President',
        email: 'ethanyxchen@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: 'Matt Hashimoto',
        leaf: 'Sebi Szafir',
        linkedin: 'https://www.linkedin.com/in/ethanchen23/',
        resume: "https://drive.google.com/file/d/1bP1CGivM06tnOQt2lyN1FWl1dVHTklul/view?usp=sharing",
        website: 'https://www.joinavanti.com/',
        blurb: "I like sports, soccer and basketball. I'm from Hong Kong and speak 1 language well and 3 languages badly. ",
    },
    {
        name: 'Shaylan Dias',
        img:  null,
        role: 'Technology Director',
        email: 'shaylandias@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: 'Shares^2',
        tree: 'Kyle Hua',
        leaf: 'Krishna Ravi, Sady Behera',
        linkedin: 'linkedin.com/in/shaylan-dias/',
        resume: 'https://drive.google.com/file/d/18bhSmX8ZJpiR0C2ecscp3rjGO5reg1qU/view',
        website: 'shaylanmdias.com',
        blurb: "Hi! I'm Shaylan, I'm an EECS major who loves swimming, backpacking and lifting! I'm also a gaming/marvel/fantasy nerd lol",
    },
    {
        name: 'Ahmed Baqai',
        img:  null,
        role: 'Technology Director',
        email: 'abaq@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: 'Hoatian Ye',
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/ahmedbaqai/',
        resume: 'https://ahmedbaqai.com/resume.pdf',
        website: 'https://ahmedbaqai.com/',
        blurb: "Hey! I'm Ahmed. You probably know that tho cause you can see my name! Does it make me cool for pointing that out? No. I love snowboarding btw!",
    },

    {
        name: 'Stephen Yang',
        img:  null,
        role: 'Industry Director',
        email: 'stephen.yang@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: null,
        tree: "Cindy Zhang",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/stephen-yang-57131185/",
        resume: null,
        website: null,
        blurb: "hello! i love mangos more than i love CS",
    },
    {
        name: 'Angela Jiang',
        img:  null,
        role: 'Finance Director',
        email: 'ajjiang@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: 'Bridget Cheng',
        leaf: 'Tiffany Feng',
        linkedin: 'linkedin.com/in/angelajjiang',
        resume: null,
        website: null,
        repeat:1,
        blurb: "Hi I'm Angela! I'm a CS and Econ major from Kansas. I really like penguins and I also enjoy baking and dancing. ",
    },
    {
        name: 'Cindy Zhang',
        img:  null,
        role: 'Education Director',
        email: 'cindyxzhang@berkeley.edu',
        year: 'Senior',
        committee: 'Education',
        project: null,
        tree: "Matt",
        leaf: "Stephen",
        linkedin: "https://www.linkedin.com/in/cindy-x-zhang/",
        resume: "https://cindyzhang977.github.io/cxz/static/media/resume.0903f5f7.pdf",
        website: "https://cindyzhang977.github.io/cxz/#/",
        blurb: "I have an unhealthy obsession with going to the beach. Whenever I get the chance, I enjoy spending my time outdoors and exploring new places, capturing picturesque views on my phone (this cost me a parking ticket once).",
        // repeat: '2',
    },
    {
        name: 'Andrew Wang',
        img:  null,
        role: 'Education Director',
        email: 'andrew.wang334@berkeley.edu',
        year: 'Senior',
        committee: 'Education',
        project: null,
        tree: 'Anthony Zhou',
        leaf: "Michelle Lin",
        linkedin: 'linkedin.com/in/andrew-wang-cal/',
        resume: null,
        website: null,
        blurb: "My name is Andrew, and I am a junior from Auburn, AL. I've been in Codeology since my second semester freshman year and I've loved my time in the club.",
    },
    {
        name: 'Amy Huang',
        img:  null,
        role: 'Web Director',
        year: 'Junior',
        committee: 'Web!',
        email: 'amyxjhuang@berkeley.edu',
        project: null,
        tree: 'Anna',
        leaf: 'Tiffanie',
        linkedin: 'https://www.linkedin.com/in/amyxjhuang/',
        resume: 'tinyurl.com/amyhuangresume',
        website: 'amyhuang.web.app',
        blurb: 'I love tasty pot, smoothie, hot cheeto puffs, animal crossing, moffitt 1st floor!!! ',
    },
    {
        name: 'David Lim',
        img:  null,
        role: 'Media Director',
        repeat: '2',
        email: 'david.lim@berkeley.edu',
        year: 'Sophomore',
        committee: "Media",
        project:  null,
        tree: "Satiya Kem",
        leaf: null,
        linkedin: null,
        resume: null,
        website: "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstleyVEVO",
        blurb: "hey yooo wassup",
    },
    {
        name: 'Jasmine Ang',
        img:  null,
        role: 'Social Director',
        year: 'Junior',
        email: 'jasmineang@berkeley.edu',
        committee: 'Social',
        project: null,
        tree: 'Jasper',
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Kristie Lin',
        img:  null,
        role: 'Social Director',
        year: 'Senior',
        email: 'kristielin13@berkeley.edu',
        committee: 'Social',
        project: null,
        tree: 'Alma',
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Larissa Tsai',
        img:  null,
        role: 'Member Relations Director',
        email: 'lari.tsai@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: null,
        tree: "Vidya",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/larissatsai/",
        resume: null,
        website: null,
        blurb: "Hi! I'm Larissa, an intended CS major from Maryland. I spend my time scrolling through Instagram looking at cute animals. I also like baking, crosswords, and my Spotify playlists:) ",
    },
    {
        name: 'Jasper Chen',
        img:  null,
        role: 'Member Relations Director',
        email: 'jasperchen3@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: 'Susan',
        leaf: 'Jasmine',
        linkedin: null,
        resume: null,
        website: null,
        blurb: "I, like everyone else, had a bit of trouble thinking up a blurb to put, but unlike everyone else, could not end up deciding on something :/",
    },
]

export const projectLeaders = [
    {
        name: 'Daniel Tseng',
        img:  null,
        role: 'Project Manager',
        email: 'danieltseng1529@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: 'Richard Huang',
        leaf: 'Roger Zhang',
        linkedin: "https://www.linkedin.com/in/dtseng1529/",
        resume: null,
        website: null,
        blurb: "Hi, I'm Daniel. I enjoy playing video games, board games, and mahjong, and also love skiing.",
    },
    {
        name: 'Krishna Ravi',
        img:  null,
        role: 'Project Manager',
        year: 'Senior',
        email: 'krishnaravi@berkeley.edu',
        committee: null,
        project: null,
        tree: "Shaylan Dias",
        leaf: "Pradeep Muthaiya",
        linkedin: "https://www.linkedin.com/in/krishna-ravi99/",
        resume: null,
        website: null,
        blurb: "Hi! I am a senior studying EECS and Data Science. Catch me @ first floor Moffitt getting absolutely nothing done.",
    },
    {
        name: 'Vidhi Chander',
        img:  null,
        role: 'Project Manager',
        year: 'Senior',
        email: 'vidhichander@berkeley.edu',
        committee: null,
        project: null,
        tree: "Vaib",
        leaf: "Erin",
        linkedin: "https://www.linkedin.com/in/vidhi-chander-952129166/",
        resume: null,
        website: null,
        blurb: "Hey! I'm Vidhi and I'm currently a senior at Berkeley studying Computer Science and Astrophysics :)",
    },
    {
        name: 'Allen Gu',
        img:  null,
        role: 'Project Leader',
        email: 'allengu01@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: 'FlapPy',
        tree: "Dustin Luong",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/allengu01/",
        resume: "https://drive.google.com/file/d/1R0zDAxJOjccr_bWXyYxufrwdSp05jmOh/view?usp=sharing",
        website: "https://allengu01.github.io/",
        blurb: "Hi, I'm Allen! I'm a sophomore studying EECS who enjoys learning new things, listening to music, and meeting new people!",
    },
    {
        name: 'Sami Oh',
        img:  null,
        role: 'Project Leader',
        email: 'haotiany@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: 'Build-A-Bear',
        tree: "Grace Altree",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/samantha-oh-3315b31b7/",
        resume: null,
        website: null,
        blurb: "I'm a sophomore interested in web design and development! I love cats, painting, and sitting in the sun :)",
    },
    {
        name: 'Sebastiaan Szafir',
        img:  null,
        role: 'Project Leader',
        year: 'Sophomore',
        email: "ethanyxchen@berkeley.edu",
        committee: null,
        project: 'ClassifAI',
        tree: "ETHAN!!!",
        leaf: "none yet </3",
        linkedin: null,
        resume: null,
        website: "https://zubatomic.com",
        blurb: "I love the number 42, and I think you should too. I'm from Spain, love programming, board games, anime and have growing suspicions towards Berkeley's parking meters.",
    },
    {
        name: 'Stephen Yang',
        img: null,
        role: 'Project Leader',
        year: "Sophomore",
        committee: null,
        project: null,
        tree: "Cindy Zhang",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/stephen-yang-57131185/",
        resume: null,
        website: null,
        blurb: "hello! i love mangos more than i love CS",
    },
    {
        name: 'Tiffanie Chau',
        img:  null,
        role: 'Project Leader',
        email: null,
        year: 'Sophomore',
        committee: null,
        project: "Spotify-ology",
        tree: "Amy Huang",
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: " Hi! I'm intending to major in CS, but besides that, I love long walks, good food, dramatic reality tv shows, and spotify playlists that put me in the feels. Also always down to meet and talk to people!",
    },
    {
        name: 'Kamille Dyan Fernando',
        img:  null,
        role: 'Project Leader',
        year: 'Junior',
        email: 'kamillef@berkeley.edu',
        committee: null,
        project: null,
        tree: 'Tiffany',
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Jun Hee Han',
        img:  null,
        role: 'Project Leader',
        email: 'junheehan@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: "Pro-Bono",
        tree: "Emily Wang",
        leaf: "Ernest Goh",
        linkedin: "https://www.linkedin.com/in/jun-hee-han-029527145/",
        resume: null,
        website: null,
        blurb: "I like to play video games and run. I reread the Harry Potter series during quarantine, those books are so good.",
    },
    {
        name: 'Trevor Baba',
        img:  null,
        role: 'Project Leader',
        year: 'Senior',
        committee: null,
        project: "Pro-Bono",
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
]

const a = [
    {
        name: 'Ada Hu',
        img:  null,
        role: 'Active Member',
        year: 'Senior',
        email: 'adahu@berkeley.edu',
        committee: null,
        project: null,
        tree: "Jennifer Xiao",
        leaf: "Ashley Chu",
        linkedin: null,
        resume: null,
        website: "https://ada-hu.github.io/",
        blurb: "uwu",
    },
    {
        name: 'Aarushi Karandikar',
        img:  null,
        role: 'Active Member',
        email: 'aarushi.k@berkeley.edu ',
        year: 'Senior',
        committee: null,
        project: null,
        tree: "Anna Young",
        leaf: "Mallika Parulekar",
        linkedin: "https://www.linkedin.com/in/aarushi-k/",
        resume: null,
        website: null,
        blurb: "certified library card holder",
    },
    {
       name: 'Ali Matsumoto',
       img:  null,
       role: 'Active Member',
       email: 'aliciamatsumoto@berkeley.edu',
       year: 'Junior',
       committee: null,
       project: null,
       tree: 'Michael Chen (we miss him)',
       leaf: null,
       linkedin: 'linkedin.com/in/aliciamatsumoto',
       resume: null,
       website: null,
       blurb: 'send me song recs & cheesy pinterest quotes <3',
   },
    {
        name: 'Amogh Maganahalli',
        img:  null,
        role: 'Active Member',
        email: 'amoghm2@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: "Shares Squared",
        tree: "Varun Murthy",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/amogh-maganahalli-4856a31a8/",
        resume: null,
        website: null,
        blurb: "I really enjoy playing sports, watching/listening to different shows and music, and just having a fun time. Hit me up with any cool science or sci-fi facts!",
    },
    {
        name: 'Ashley Chu',
        img:  null,
        role: 'Active Member',
        email: 'ashchu@berkeley.edu',
        repeat: '2',
        year: 'Junior',
        committee: 'Website',
        project: null,
        tree: 'Adadadadada',
        leaf: 'Mayaaaaaaa',
        linkedin: 'https://linkedin.com/in/ashley-chu',
        resume: 'https://ashchu.github.io/Chu_Ashley_Resume.pdf',
        website: 'https://ashchu.github.io/',
        blurb: "Hi! My name's Ashley and I love egg tarts + animated films :)",
    },
    {
        name: 'Chetan Khanna',
        img: null,
        role: 'Active Member',
        email: 'chetan.khanna@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'CJ Manna',
        img:  null,
        role: 'Active Member',
        year: 'Senior',
        email: 'charlesmanna@berkeley.edu',
        committee: null,
        project: null,
        tree: 'Micah',
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "Talk to me about hiking, movies, and ethical design!",
    },
    {
        name: 'Cynthia Lan',
        img:  null,
        role: 'Active Member',
        year: "Sophomore",
        email: 'cynthialan@berkeley.edu',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Dustin Luong',
        img:  null,
        role: 'Active Member',
        email: 'dstn.luong@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Eric Peng',
        img:  null,
        role: 'Active Member',
        year: null,
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Erin Tsai',
        img:  null,
        role: 'Active Member',
        email: 'ertsai01@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: 'Vidhi',
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/erin-tsai-9b5a28167/',
        resume: null,
        website: null,
        blurb: "I love music and drinking/spilling tea! Feel free to email me any time and say hello :)",
    },
    {
        name: 'Ernest Goh',
        img:  null,
        role: 'Active Member',
        email: 'ernest.goh20@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Jimmy Lee',
        img: null,
        role: 'skrillexmaster',
        email: 'jimmyminhlee@gmail.com',
        year: "Senior",
        committee: null,
        project: null,
        tree: 'David Ly',
        leaf: "Pranav P",
        linkedin: "linkedin.com/jimmyminhlee",
        resume: "https://open.spotify.com/playlist/2sD0RepeZrFaabSBAjzg6w?si=2dKoiN57QJ-KP-7S5w_XAA ",
        website: "jimmyminhlee.github.io",
        blurb: "vintage everything check out the spotify (edit from web- click the resume button LOL)",
    },
    {
        name: 'Kamille Dyan Fernando',
        img:  null,
        role: 'Active Member',
        email: 'kamillef@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Grace Altree',
        img:  null,
        role: 'Active Member',
        email: 'gracealtree@berkeley.edu',
        year: "Senior",
        committee: null,
        project: null,
        tree: "Srishti Goswamy",
        leaf: "Sami Oh",
        linkedin: "https://www.linkedin.com/in/grace-altree/",
        resume: null,
        website: null,
        blurb: "Here are some of my favorite ways to procrastinate coding: dancing, trying a new restaurant, playing banana grams, going to the beach, reading, sleeping... the list goes on.   ",
    },
    {
        name: 'Kyle Hua',
        img:  null,
        role: 'Active Member',
        email: 'kylehuuuaaa@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },

    {
        name: 'Mallika Parulekar',
        img:  null,
        role: 'Active Member',
        email: 'mallika.parulekar@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: "Shares^2",
        tree: "Aarushi",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/mallikaparulekar/",
        resume: null,
        website: null,
        blurb: "Hello! I'm Mallika and I'm an intended CS major who likes building new things, and I'm interested in exploring full stack development, machine learning and law. oh and also boba shops :)",
    },
    {
        name: 'Mantej Panesar',
        img:  null,
        role: 'Active Member',
        email: 'mantejpanesar@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Matt Hashimoto',
        img:  null,
        role: 'Active Member',
        email: 'matth1290@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: 'Calvin',
        leaf: 'Ethan, Cindy',
        linkedin: 'https://www.youtube.com/watch?v=QtBDL8EiNZo',
        resume: null,
        website: 'https://www.joinavanti.com/',
        blurb: "Check out my awesome Linkedin (click above). ",
    },
    {
        name: 'Maya Zheng',
        img:  null,
        role: 'Active Member',
        year: "Sophomore",
        committee: null,
        project: "Find your zen",
        tree: "Ashley Chu",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/maya-zheng-15868b208 ",
        resume: null,
        website: null,
        blurb: "Movie nerd, bubble tea, matcha and roller coaster enthusiast. I'm also pretty interested in 3D graphics and animation. ",
    },
    {
        name: 'Pradeep Muthaiya',
        img:  null,
        role: 'Active Member',
        year: 'Junior',
        committee: null,
        project: "Shares^2",
        tree: "Krishna, Shaylan, Kyle, Karthick, Sree, Vaib, etc.",
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "CS and Stats Sophomore from SoCal just vibing. Hmu if ur in LA and wanna grab food :)",
    },
    {
        name: 'Roger Zhang',
        img:  null,
        role: 'Active Member',
        year: "Senior",
        committee: null,
        project: null,
        tree: "Daniel Tseng",
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "Hey! I'm Roger a EECS major who also loves consulting and music! I also love adrenaline activities like rollercoasters, snowboarding, and skydiving!",
    },
    {
        name: 'Sadyant Behera',
        img:  null,
        role: 'Active Member',
        year: "Junior",
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Saketh Kollu',
        img:  null,
        role: 'Active Member',
        year: null,
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Satiya Kem',
        img:  null,
        role: 'Active Member',
        year: "Senior",
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },

    {
        name: 'Taylor Yoo',
        img:  null,
        role: 'Active Member',
        year: "Senior",
        committee: null,
        project: null,
        tree: "Ayush",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/taylor-yoo/",
        resume: null,
        website: null,
        blurb: "Hi my name is Taylor! I'm majoring in Molecular and Cellular Biology and minoring in Public Health!  I really enjoy playing basketball and volleyball, making avocado toast, and going to the beach with friends :)",
    },
    {
        name: 'Tiffany Chung',
        img: null,
        role: 'Active Member',
        year: 'Senior',
        committee: null,
        project: null,
        tree: "Jess",
        leaf: "Kamille",
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Tiffany Feng',
        img: null,
        role: 'Active Member',
        repeat: '2',
        year: 'Junior',
        committee: null,
        project: null,
        tree: "Angela Jiang",
        leaf: null,
        linkedin: "www.linkedin.com/in/tiffanylinyifeng",
        resume: null,
        website: null,
        blurb: "Hello! I like tacos, Golden Retrievers, and long walks on the beach",
    },
    {
        name: 'Trevor Baba',
        img:  null,
        role: 'Active Member',
        year: null,
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Vaibhav Gattani',
        img:  null,
        role: 'Active Member',
        email: 'vaibg@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Varun Murthy',
        img:  null,
        role: 'Active Member',
        year: 'Senior',
        committee: null,
        project: null,
        tree: "none",
        leaf: "Amogh",
        linkedin: "https://www.linkedin.com/in/varun-r-murthy/",
        resume: null,
        website: null,
        blurb: "I've been in Codeology since my second semester. Alongside EECS, I'm also doing a music minor!",
    },
 ];

function compare(a, b) {
    const nameA = a.name.toUpperCase();
    const nameB = b.name.toUpperCase();

    let comparison = 0;
    if (nameA > nameB) {
        comparison = 1;
    } else if (nameA < nameB) {
        comparison = -1;
    }
    return comparison;
}

const insertImg = (persons) => {
    for(let i = 0; i < persons.length; i++) {
        var obj = persons[i];
        const first = obj.name.split(" ")[0].toLowerCase() + (obj.hasOwnProperty('repeat') ? obj.repeat : '')
        console.log(first);
        try {
            obj.img = require('./images/' + 'people/' + first + '.jpg');
        } catch {
            obj.img = require('./images/people/default.jpg');
        }
    }
}

a.sort(compare);
insertImg(leadership);
insertImg(projectLeaders);
insertImg(a);
export const actives = a;
