export const leadership = [
    {
        name: 'Vidya Ganga',
        img:  null,
        role: 'President',
        year: 'Junior',
        email: 'sreevidyaganga0@berkeley.edu',
        committee: null,
        project: null,
        tree: 'Karthick',
        leaf: 'Larissa',
        linkedin: 'https://www.linkedin.com/in/sreevidya-ganga-70113076/',
        resume: null,
        website: null,
        blurb: 'hi i <3 oatmeal and warm hugs ',
    },
    {
        name: 'Ethan Chen',
        img:  null,
        role: 'Vice President',
        email: 'ethanyxchen@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: 'SeaWarden led by Jun Hee',
        tree: 'Matt Hashimoto!',
        leaf: 'Sebi Szafir',
        linkedin: 'https://www.linkedin.com/in/ethanchen23/',
        resume: "https://tinyurl.com/resumeEthanChen",
        website: 'https://www.joinavanti.com/',
        blurb: "I'm from and grew up in Hong Kong and I really like sports like soccer, basketball, tennis and F1! Codeology has given me so much, especially finding a community of friends as well as resources to help me in my CS career! ",
    },
    {
        name: 'Shaylan Dias',
        img:  null,
        role: 'Technology Director',
        email: 'shaylandias@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: 'Shares^2',
        tree: 'Kyle Hua',
        leaf: 'Krishna Ravi, Sady Behera',
        linkedin: 'https://linkedin.com/in/shaylan-dias/',
        resume: 'https://drive.google.com/file/d/18bhSmX8ZJpiR0C2ecscp3rjGO5reg1qU/view',
        website: 'https://shaylanmdias.com',
        blurb: "Hi! I'm Shaylan, I'm an EECS major who loves swimming, backpacking and lifting! I'm also a gaming/marvel/fantasy nerd lol",
    },
    {
        name: 'Ahmed Baqai',
        img:  null,
        role: 'Technology Director',
        email: 'abaq@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null, 
        tree: 'Hoatian Ye',
        leaf: null, 
        linkedin: 'https://www.linkedin.com/in/ahmedbaqai/', 
        resume: 'https://ahmedbaqai.com/resume.pdf', 
        website: 'https://ahmedbaqai.com/',
        blurb: "Hey! I'm Ahmed. You probably know that tho cause you can see my name! Does it make me cool for pointing that out? No. I love snowboarding btw!",
    },

    {
        name: 'Stephen Yang',
        img:  null,
        role: 'Industry Director',
        email: 'stephen.yang@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: "ClassifAI",
        tree: "Cindy Zhang",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/stephen-yang-/",
        resume: null,
        website: null,
        blurb: "hello my name is stephen ",
    },
    {
        name: 'Angela Jiang',
        img:  null,
        role: 'Finance Director',
        email: 'ajjiang@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: 'Bridget Cheng',
        leaf: 'Tiffany Feng',
        linkedin: 'https://linkedin.com/in/angelajjiang',
        resume: null,
        website: null,
        repeat:1,
        blurb: "Hi I'm Angela! I'm a CS and Econ major from Kansas. I really like penguins and I also enjoy baking and dancing. ",
    },
    {
        name: 'Cindy Zhang',
        img:  null,
        role: 'Education Director',
        email: 'cindyxzhang@berkeley.edu',
        year: 'Senior',
        committee: 'Education',
        project: null,
        tree: "Matt",
        leaf: "Stephen",
        linkedin: "https://www.linkedin.com/in/cindy-x-zhang/",
        resume: "https://cindyzhang977.github.io/cxz/static/media/resume.0903f5f7.pdf",
        website: "https://cindyzhang977.github.io/cxz/#/",
        blurb: "I have an unhealthy obsession with going to the beach. Whenever I get the chance, I enjoy spending my time outdoors and exploring new places, capturing picturesque views on my phone (this cost me a parking ticket once).",
        // repeat: '2',
    },
    {
        name: 'Andrew Wang',
        img:  null,
        role: 'Education Director',
        email: 'andrew.wang334@berkeley.edu',
        year: 'Senior',
        committee: 'Education',
        project: null,
        tree: 'Anthony Zhou',
        leaf: "Michelle Lin",
        linkedin: 'https://linkedin.com/in/andrew-wang-cal/',
        resume: null,
        website: null,
        blurb: "My name is Andrew, and I am a junior from Auburn, AL. I've been in Codeology since my second semester freshman year and I've loved my time in the club.",
    },
    {
        name: 'Amy Huang',
        img:  null,
        role: 'Web Director',
        year: 'Junior',
        committee: 'Web!',
        email: 'amyxjhuang@berkeley.edu',
        project: null,
        tree: 'Anna',
        leaf: 'Tiffanie <3 :3',
        linkedin: 'https://www.linkedin.com/in/amyxjhuang/',
        resume: 'https://tinyurl.com/amyhuangresume',
        website: 'https://amyhuang.web.app',
        blurb: 'I love tasty pot, smoothie, hot cheeto puffs, animal crossing, moffitt 1st floor!!! ',
    },
    {
        name: 'David Lim',
        img:  null,
        role: 'Media Director',
        repeat: '2',
        email: 'david.lim@berkeley.edu',
        year: 'Sophomore',
        committee: "Media",
        project:  "Sea Warden",
        tree: "Satiya Kem",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/davidlim7391/",
        resume: null,
        website: "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstleyVEVO",
        blurb: "yup yip yep yap yop",
    },
    {
        name: 'Jasmine Ang',
        img:  null,
        role: 'Social Director',
        year: 'Junior',
        email: 'jasmineang@berkeley.edu',
        committee: 'Social',
        project: null,
        tree: 'Jasper',
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Kristie Lin',
        img:  null,
        role: 'Social Director',
        year: 'Senior',
        email: 'kristielin13@berkeley.edu',
        committee: 'Social',
        project: null,
        tree: 'Alma',
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Larissa Tsai',
        img:  null,
        role: 'Member Relations Director',
        email: 'lari.tsai@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: null,
        tree: "Vidya",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/larissatsai/",
        resume: null,
        website: null,
        blurb: "Hi! I'm Larissa, an intended CS major from Maryland. I spend my time scrolling through Instagram looking at cute animals. I also like baking, crosswords, and my Spotify playlists:) ",
    },
    {
        name: 'Jasper Chen',
        img:  null,
        role: 'Member Relations Director',
        email: 'jasperchen3@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: 'Susan',
        leaf: 'Jasmine',
        linkedin: null,
        resume: null,
        website: null,
        blurb: "I, like everyone else, had a bit of trouble thinking up a blurb to put, but unlike everyone else, could not end up deciding on something :/",
    },
]

export const projectLeaders = [
    {
        name: 'Daniel Tseng',
        img:  null,
        role: 'Project Manager',
        email: 'danieltseng1529@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: 'Richard Huang',
        leaf: 'Roger Zhang',
        linkedin: "https://www.linkedin.com/in/dtseng1529/",
        resume: null,
        website: null,
        blurb: "Hi, I'm Daniel. I enjoy playing video games, board games, and mahjong, and also love skiing.",
    },
    {
        name: 'Krishna Ravi',
        img:  null,
        role: 'Project Manager',
        year: 'Senior',
        email: 'krishnaravi@berkeley.edu',
        committee: null,
        project: null,
        tree: "Shaylan Dias",
        leaf: "Pradeep Muthaiya",
        linkedin: "https://www.linkedin.com/in/krishna-ravi99/",
        resume: null,
        website: null,
        blurb: "Hi! I am a senior studying EECS and Data Science. Catch me @ first floor Moffitt getting absolutely nothing done.",
    },
    {
        name: 'Vidhi Chander',
        img:  null,
        role: 'Project Manager',
        year: 'Senior',
        email: 'vidhichander@berkeley.edu',
        committee: null,
        project: null,
        tree: "Vaib",
        leaf: "Erin",
        linkedin: "https://www.linkedin.com/in/vidhi-chander-952129166/",
        resume: null,
        website: null,
        blurb: "Hey! I'm Vidhi and I'm currently a senior at Berkeley studying Computer Science and Astrophysics :)",
    },
    {
        name: 'Allen Gu',
        img:  null,
        role: 'Project Leader',
        email: 'allengu01@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: 'FlapPy',
        tree: "Dustin Luong",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/allengu01/",
        resume: "https://drive.google.com/file/d/1R0zDAxJOjccr_bWXyYxufrwdSp05jmOh/view?usp=sharing",
        website: "https://allengu01.github.io/",
        blurb: "Hi, I'm Allen! I'm a sophomore studying EECS who enjoys learning new things, listening to music, and meeting new people!",
    },
    {
        name: 'Sami Oh',
        img:  null,
        role: 'Project Leader',
        email: 'haotiany@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: 'Build-A-Bear',
        tree: "Grace Altree",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/samantha-oh-3315b31b7/",
        resume: null,
        website: null,
        blurb: "I'm a sophomore interested in web design and development! I love cats, painting, and sitting in the sun :)",
    },
    {
        name: 'Sebastiaan Szafir',
        img:  null,
        role: 'Project Leader',
        year: 'Sophomore',
        email: "",
        committee: null,
        project: 'ClassifAI',
        tree: "ETHAN!!!",
        leaf: "none yet </3",
        linkedin: null,
        resume: null,
        website: "https://zubatomic.com",
        blurb: "I love the number 42, and I think you should too. I'm from Spain, love programming, board games, anime and have growing suspicions towards Berkeley's parking meters.",
    },
    {
        name: 'Stephen Yang',
        img: null,
        role: 'Project Leader',
        year: "Sophomore",
        committee: null,
        project: null,
        tree: "Cindy Zhang",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/stephen-yang-57131185/",
        resume: null,
        website: null,
        blurb: "hello! i love mangos more than i love CS",
    },
    {
        name: 'Tiffanie Chau',
        img:  null,
        role: 'Project Leader',
        email: 'tiffaniechau@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: "Beary Hungry",
        tree: "ONLY THE BEST: AMY HUANG",
        leaf: "not ready to be a mother yet...",
        linkedin: "https://www.linkedin.com/in/tiffanielchau/",
        resume: null,
        website: null,
        blurb: "I'm a simple girl; there are three things I love: good food, opening packages, and being around awesome people. Codeology fulfills 2 out of those three things which makes me very happy. :) I'm interested in exploring the tech industry while deciding what to do with my life in college. ",
    },
    {
        name: 'Kamille Dyan Fernando',
        img:  null,
        role: 'Project Leader',
        year: 'Junior',
        email: 'kamillef@berkeley.edu',
        committee: null,
        project: null,
        tree: 'Tiffany',
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Jun Hee Han',
        img:  null,
        role: 'Project Leader',
        email: 'junheehan@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: "Seawarden",
        tree: "Emily Wang",
        leaf: "Ernest Goh",
        linkedin: "https://www.linkedin.com/in/jun-hee-han-029527145/",
        resume: null,
        website: "https://instagram.com/junheehan",
        blurb: "I am a senior studying computer science.",
    },
    {
        name: 'Trevor Baba',
        img:  null,
        role: 'Project Leader',
        email:'trevor.baba@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: "Pro-Bono",
        tree: 'Sherman',
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/trevor-baba-000/',
        resume: null,
        website: null,
        blurb: 'I love playing basketball and collecting NFTs.',
    },
]

const a = [
    {
        name: 'Ashley Eastman',
        img:  null,
        role: 'Active Member',
        year: 'Junior',
        email: 'ashleyha@berkeley.edu',
        repeat: "3",
        committee: null,
        project: null,
        tree: "",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/ashleyeastman/",
        resume: null,
        website: null,
        blurb: "I love cooking for my friends, working out/doing handstands, and exploring the world! Fun fact: I know how to evacuate a full airplane in 90 seconds. A few favs~ Artist: Sam Cooke ~ Book: Les Miserables ~ Movie: Phantom of the Opera",
    },
    {
        name: 'Ada Hu',
        img:  null,
        role: 'Active Member',
        year: 'Senior',
        email: 'adahu@berkeley.edu',
        committee: null,
        project: "Avanti",
        tree: "Jennifer Xiao",
        leaf: "Ashley Chu",
        linkedin: null,
        resume: null,
        website: "https://ada-hu.github.io/",
        blurb: "Hi hehe I'm a senior pls talk to me im bored",
    },
    {
        name: 'Aarushi Karandikar',
        img:  null,
        role: 'Active Member',
        email: 'aarushi.k@berkeley.edu ',
        year: 'Senior',
        committee: null,
        project: null,
        tree: "Anna Young",
        leaf: "Mallika Parulekar",
        linkedin: "https://www.linkedin.com/in/aarushi-k/",
        resume: null,
        website: null,
        blurb: "certified library card holder",
    },
    {
        name: 'Alan Liu',
        img:  null,
        role: 'Active Member',
        email: 'alanliu2345@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: 'Build A Bear',
        tree: 'me',
        leaf: 'Kevin Nguyen',
        linkedin: 'https://www.linkedin.com/in/alan-liu-20/',
        resume: null,
        website: null,
        blurb: 'I like kbbq and boba, will beat you in smash, and listen to a lot of edm/hip hop',
    }, 
    {
        name: 'Ali Matsumoto',
        img:  null,
        role: 'Active Member',
        email: 'aliciamatsumoto@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: 'Michael Chen (we miss him)',
        leaf: null,
        linkedin: 'https://linkedin.com/in/aliciamatsumoto',
        resume: null,
        website: null,
        blurb: 'send me song recs & cheesy pinterest quotes <3',
    },
    {
        name: 'Amogh Maganahalli',
        img:  null,
        role: 'Active Member',
        email: 'amoghm2@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: "Avanti",
        tree: "Varun Murthy",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/amogh-maganahalli-4856a31a8/",
        resume: null,
        website: "https://www.instagram.com/amoghmaganahalli_/",
        blurb: "Yo! I'm a sophomore but this is still my first year in Berkeley! I really enjoy watching different kinds of shows (particularly sci-fi and comedy), playing video games, playing/following sports, and listening to music. If you wanna explore Berkeley or even just chill and talk or walk around, feel free to hmu! ",
    },
    {
        name: 'Ashley Chang',
        img:  null,
        role: 'Active Member',
        email: 'ashleychang@berkeley.edu',
        repeat: '4',
        year: 'Junior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "hi! im ash and some things i love are pocket camp, music (day6, keshi, lots of mandopop), and pudding from 7-11 in taiwan:') i also enjoy running (sometimes) and cooking!",
    },
    {
        name: 'Ashley Chu',
        img:  null,
        role: 'Active Member',
        email: 'ashchu@berkeley.edu',
        repeat: '2',
        year: 'Junior',
        committee: 'Website',
        project: null,
        tree: 'Adadadadada',
        leaf: 'Mayaaaaaaa',
        linkedin: 'https://linkedin.com/in/ashley-chu',
        resume: 'https://ashchu.github.io/Chu_Ashley_Resume.pdf',
        website: 'https://ashchu.github.io/',
        blurb: "Hi! My name's Ashley and I love egg tarts + animated films :)",
    },
    {
        name: 'Chanbin Park',
        img: null,
        role: 'Active Member',
        email: 'chanbin.park@berkeley.edu',
        year: 'Freshman',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: "https://www.linkedin.com/in/chanbin-park-4b795920b/",
        resume: null,
        website: "https://chanbinpark.com/",
        blurb: "I don't like avocados cuz they're too mushy. Can we change our mascot?",
    },
    {
        name: 'Chetan Khanna',
        img: null,
        role: 'Active Member',
        email: 'chetan.khanna@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'CJ Manna',
        img:  null,
        role: 'Active Member',
        year: 'Senior',
        email: 'charlesmanna@berkeley.edu',
        committee: null,
        project: null,
        tree: 'Micah',
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "Talk to me about hiking, movies, and ethical design!",
    },
    {
        name: 'Cynthia Lan',
        img:  null,
        role: 'Active Member',
        year: "Sophomore",
        email: 'cynthialan@berkeley.edu',
        committee: "Social Committee",
        project: "Sea Warden, Build-A-Bear",
        tree: "Kristie",
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "Hi I'm Cynthia! I like going to the beach, going on spontaneous adventures and grabbing food! ",
    },
    {
        name: 'Danica Tang',
        img:  null,
        role: 'Active Member',
        email: 'danicat@berkeley.edu',
        year: 'Freshman',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/danica-t-3998741b2',
        resume: null,
        website: null,
        blurb: 'Hi! I’m Danica and I love to make crafts, play musical instruments, and bake! <3',
    },
    {
        name: 'Dustin Luong',
        img:  null,
        role: 'Active Member',
        email: 'dstn.luong@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Eric Berndt',
        img:  null,
        role: 'Active Member',
        email: 'ekberndt@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: 'ClassifAI',
        tree: '',
        repeat:'2',
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/ekberndt/',
        resume: null,
        website: null,
        blurb: "I love asking questions and learning new things :D",
    },
    {
        name: 'Erin Tsai',
        img:  null,
        role: 'Active Member',
        email: 'ertsai01@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: 'Vidhi',
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/erin-tsai-9b5a28167/',
        resume: null,
        website: 'https://ertsai01.github.io',
        blurb: "I love music and drinking/spilling tea! Feel free to email me any time and say hello :)",
    },
    {
        name: 'Ernest Goh',
        img:  null,
        role: 'Active Member',
        email: 'ernest.goh20@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    
    {
        name: 'Euhan Kim',
        img:  null,
        role: 'Active Member',
        email: 'euhan123@berkeley.edu',
        year: 'Freshman',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "I'm an outgoing food lover that loves to hang out with people. I also like to play tennis and grabbing food late at night.",
    },
    
    {
        name: 'Jimmy Lee',
        img: null,
        role: 'skrillexmaster',
        email: 'jimmyminhlee@gmail.com',
        year: "Senior",
        committee: null,
        project: null,
        tree: 'David Ly',
        leaf: "Pranav P",
        linkedin: "https://linkedin.com/jimmyminhlee",
        resume: "https://open.spotify.com/playlist/2sD0RepeZrFaabSBAjzg6w?si=2dKoiN57QJ-KP-7S5w_XAA ",
        website: "https://jimmyminhlee.github.io",
        blurb: "vintage everything check out the spotify (edit from web- click the resume button LOL)",
    },
    {
        name: 'Kamille Dyan Fernando',
        img:  null,
        role: 'Active Member',
        email: 'kamillef@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Kevin Chow',
        img:  null,
        role: 'Active Member',
        email: 'chowmein113@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: 'Beary hungry',
        tree: 'Trevor Baba',
        leaf: 'I’m a leaf',
        repeat:'2',
        linkedin: 'https://linkedin.com/in/kevin-chow-engineer/',
        resume: null,
        website: null,
        blurb: 'I’m a junior eecs transfer and I’ve been told that I am an outgoing, friendly person that likes to play/listen to music (specifically Keshi), eat good food (nothing beats Mac n’ cheese), play video games (Minecraft in particular) and watch shows (Teen Titans anyone?). ',
    },
    {
        name: 'Grace Altree',
        img:  null,
        role: 'Active Member',
        email: 'gracealtree@berkeley.edu',
        year: "Senior",
        committee: null,
        project: null,
        tree: "Srishti Goswamy",
        leaf: "Sami Oh",
        linkedin: "https://www.linkedin.com/in/grace-altree/",
        resume: null,
        website: null,
        blurb: "Here are some of my favorite ways to procrastinate coding: dancing, trying a new restaurant, playing banana grams, going to the beach, reading, sleeping... the list goes on.   ",
    },
    {
        name: 'Joelle Siong Sin',
        img:  null,
        role: 'Active Member',
        email: 'jsiongsin@berkeley.edu',
        year: "Sophomore",
        committee: null,
        project: 'ClassifAI',
        tree: "Sami!",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/joellesiongsin/",
        resume: null,
        website: null,
        blurb: "Hi! I'm a sophomore studying EECS/IEOR! I love scenic runs, Trader Joe's flowers, and finding new songs for my Spotify playlists : )",
    },
    {
        name: 'Kyle Hua',
        img:  null,
        role: 'Active Member',
        email: 'kylehuuuaaa@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },

    {
        name: 'Kevin Nguyen',
        img:  null,
        role: 'Active Member',
        email: 'kevintnguyen@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        repeat: '3',
        linkedin: null,
        resume: null,
        website: null,
        blurb: "Hi, I'm Kevin Nguyen! I love napping, watching movies/tv (my favorite shows are Simpsons and Futurama), and trying new places to eat. ",
    },

    {
        name: 'Lauren Zheng',
        img:  null,
        role: 'Active Member',
        email: 'laurenz@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: 'Build-a-bear',
        tree: null,
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/lauren-zheng-2606',
        resume: null,
        website: null,
        blurb: "I love plushies, guitars, kdramas, and tea. ",
    },
    {
        name: 'Lincoln Too',
        img:  null,
        role: 'Active Member',
        email: 'lincoln99@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: 'ClassifAI',
        tree: 'Ahmed',
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "I like anime, sports, and board games. HMU!",
    },

    {
        name: 'Mallika Parulekar',
        img:  null,
        role: 'Active Member',
        email: 'mallika.parulekar@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: "Sea Warden",
        tree: "Aarushi",
        leaf: 'Ramya Chitturi',
        linkedin: "https://www.linkedin.com/in/mallikaparulekar/",
        resume: 'https://drive.google.com/file/d/1JF8Vr_nSIWZkEu12A21TLXBcvM4YatlS/view?usp=sharing',
        website: 'https://linkedin.com/in/mallikaparulekar',
        blurb: "Hi! I'm Mallika - a sophomore studying computer science who's also interested in math, economics and the law. When I'm not drinking boba and playing tennis, you can find me building things, trying my hand at fullstack and being a human learning about machine learning :)",
    },
    {
        name: 'Mantej Panesar',
        img:  null,
        role: 'Active Member',
        email: 'mantejpanesar@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Matt Hashimoto',
        img:  null,
        role: 'Active Member',
        email: 'matth1290@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: 'Calvin',
        leaf: 'Ethan, Cindy',
        linkedin: 'https://www.youtube.com/watch?v=QtBDL8EiNZo',
        resume: null,
        website: 'https://www.joinavanti.com/',
        blurb: "Check out my awesome Linkedin (click above). ",
    },
    {
        name: 'Maya Zheng',
        img:  null,
        role: 'Active Member',
        year: "Sophomore",
        committee: null,
        project: "Find your zen",
        tree: "Ashley Chu",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/maya-zheng-15868b208 ",
        resume: null,
        website: null,
        blurb: "Movie nerd, bubble tea, matcha and roller coaster enthusiast. I'm also pretty interested in 3D graphics and animation. ",
    },
    {
    name: 'Mizuho Li',
    img:  null,
    email:'limizuho@berkeley.edu',
    role: 'Active Member',
    year: "Freshman",
    committee: null,
    project: "Build a Bear",
    tree: "Ernest Goh",
    leaf: null,
    linkedin: null,
    resume: null,
    website: null,
    blurb: "Hi I’m Mizuho! I love  playing any random sports and a BIG fan of k drama. ",
    },  
    {
        name: 'Pradeep Muthaiya',
        img:  null,
        role: 'Active Member',
        year: 'Junior',
        committee: null,
        project: "Shares^2",
        tree: "Krishna, Shaylan, Kyle, Karthick, Sree, Vaib, etc.",
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "CS and Stats Sophomore from SoCal just vibing. Hmu if ur in LA and wanna grab food :)",
    },
    
    {
        name: 'Roger Zhang',
        img:  null,
        role: 'Active Member',
        year: "Senior",
        committee: null,
        project: null,
        tree: "Daniel Tseng",
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "Hey! I'm Roger a EECS major who also loves consulting and music! I also love adrenaline activities like rollercoasters, snowboarding, and skydiving!",
    },
    {
        name: 'Rachel Xin',
        img:  null,
        role: 'Active Member',
        year: "Freshman",
        committee: null,
        email: "rachelxin@berkeley.edu",
        project: null,
        tree: null,
        leaf: null,
        linkedin: "https://www.linkedin.com/in/rachelxin",
        resume: null,
        website: null,
        blurb: "Hello! I'm Rachel, and I am an EECS major from Orange County, CA. I enjoy playing tennis, baking/cooking, and trying new things during my free time.",
    },
    {
        name: 'Ramya Chitturi',
        img:  null,
        role: 'Active Member',
        year: "Freshman",
        committee: null,
        email: "ramya.chitturi@berkeley.edu",
        project: null,
        tree: null,
        leaf: null,
        linkedin: "https://www.linkedin.com/in/ramya-s-chitturi/",
        resume: null,
        website: null,
        blurb: "https://www.linkedin.com/in/ramya-s-chitturi/",
    },
    {
        name: 'Sadyant Behera',
        img:  null,
        email:'sadyant.behera@berkeley.edu',
        role: 'Active Member',
        year: "Junior",
        committee: null,
        project: 'sea warden',
        tree: 'shaylan dias',
        leaf: null,
        linkedin: 'https://linkedin.com/in/sadyant',
        resume: null,
        website: 'https://GitHub.com/sadyant',
        blurb: 'i am huge.',
    },
    {
        name: 'Saketh Kollu',
        img:  null,
        role: 'Active Member',
        year: null,
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Satiya Kem',
        img:  null,
        role: 'Active Member',
        year: "Senior",
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Shannon Or',
        img:  null,
        role: 'Active Member',
        year: "Sophomore",
        email:"shannonor@berkeley.edu",
        committee: null,
        project: "beary hungry",
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "i love to eat, play basketball and try new things ",
    },

    {
        name: 'Taylor Yoo',
        img:  null,
        role: 'Active Member',
        year: "Senior",
        committee: null,
        project: null,
        tree: "Ayush",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/taylor-yoo/",
        resume: null,
        website: null,
        blurb: "Hi my name is Taylor! I'm majoring in Molecular and Cellular Biology and minoring in Public Health!  I really enjoy playing basketball and volleyball, making avocado toast, and going to the beach with friends :)",
    },
    {
        name: 'Tiffany Chung',
        img: null,
        role: 'Active Member',
        year: 'Senior',
        committee: null,
        project: null,
        tree: "Jess",
        leaf: "Kamille",
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Tiffany Feng',
        img: null,
        email:"tiffanylinyifeng@berkeley.edu",
        role: 'Active Member',
        repeat: '2',
        year: 'Junior',
        committee: null,
        project: 'Beary-Hungry',
        tree: "Angela Jiang",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/tiffanylinyifeng",
        resume: null,
        website: null,
        blurb: "Hi! I'm Tiffany, and I'm a Junior studying Computer Science and Business. I'm from San Diego, and I love being outdoors, baking, and traveling :)Hello! I like tacos, Golden Retrievers, and long walks on the beach",
    },
    {
        name: 'Vaibhav Gattani',
        img:  null,
        role: 'Active Member',
        email: 'vaibg@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Varun Murthy',
        img:  null,
        role: 'Active Member',
        year: 'Senior',
        committee: null,
        project: null,
        tree: "none",
        leaf: "Amogh",
        linkedin: "https://www.linkedin.com/in/varun-r-murthy/",
        resume: null,
        website: null,
        blurb: "I've been in Codeology since my second semester. Alongside EECS, I'm also doing a music minor!",
    },
 ];

function compare(a, b) {
    const nameA = a.name.toUpperCase();
    const nameB = b.name.toUpperCase();

    let comparison = 0;
    if (nameA > nameB) {
        comparison = 1;
    } else if (nameA < nameB) {
        comparison = -1;
    }
    return comparison;
}

const insertImg = (persons) => {
    for(let i = 0; i < persons.length; i++) {
        var obj = persons[i];
        const first = obj.name.split(" ")[0].toLowerCase() + (obj.hasOwnProperty('repeat') ? obj.repeat : '')
        try {
            obj.img = require('../images/members/' + first + '.jpg');
        } catch {
            obj.img = require('../images/members/default.jpg');
        }
    }
}

a.sort(compare);
insertImg(leadership);
insertImg(projectLeaders);
insertImg(a);
export const actives = a;
