/* NOTE: make sure links have https:// in front or they will not work */

export const leadership = [
    {
        name: 'Daniel Tseng',
        img:  null,
        role: 'President',
        email: 'danieltseng1529@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: 'Richard Huang',
        leaf: 'Roger Zhang, Lauren Zheng',
        linkedin: "https://www.linkedin.com/in/dtseng1529/",
        resume: null,
        website: null,
        blurb: "Hi, I'm Daniel. I enjoy playing video games, board games, and mahjong, and also love skiing.",
    },
    {
        name: 'Jasper Chen',
        img:  null,
        role: 'Vice President',
        email: 'jasperchen3@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: 'Susan',
        leaf: 'Jasmine',
        linkedin: 'https://www.linkedin.com/in/jasper-chen-843299197/',
        resume: null,
        website: null,
        blurb: "catch me outside sweetheart with the black milk tea half ice no toppings",
    },
    {
        name: 'Allen Gu',
        img:  null,
        role: 'Tech Director',
        email: 'allengu01@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: 'FlapPy',
        tree: "Dustin Luong",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/allengu01/",
        resume: "https://drive.google.com/file/d/1R0zDAxJOjccr_bWXyYxufrwdSp05jmOh/view?usp=sharing",
        website: "https://allengu01.github.io/",
        blurb: "hi, i'm Allen! i'm a second-year studying EECS from illinois. i like card games, music, and food.",
    },
    {
        name: 'Sebastiaan Szafir',
        img:  null,
        role: 'Tech Director',
        year: 'Sophomore',
        email: "sebastiaan@berkeley.edu",
        committee: null,
        project: 'ClassifAI',
        tree: "Ethan",
        leaf: "None yet",
        linkedin: 'https://www.linkedin.com/in/sebastiaan-szafir-fridman/',
        resume: null,
        website: "https://sebiszafir.com/",
        blurb: "I love the number 42, and I think you should too. I'm from Spain, love programming, board games, anime and have growing suspicions towards Berkeley's parking meters.",
    },
    {
        name: 'Angela Jiang',
        img:  null,
        role: 'Education Director',
        email: 'ajjiang@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: 'Bridget Cheng',
        leaf: 'Tiffany Feng',
        linkedin: 'https://linkedin.com/in/angelajjiang',
        resume: null,
        website: null,
        repeat:1,
        blurb: "Hi I'm Angela! I'm a CS and Econ major from Kansas. I really like penguins and I also enjoy baking and dancing. ",
    },
    {
        name: 'Cindy Zhang',
        img:  null,
        role: 'Education Director',
        email: 'cindyxzhang@berkeley.edu',
        year: 'Senior',
        committee: 'Education',
        project: null,
        tree: "Matt",
        leaf: "Stephen",
        linkedin: "https://www.linkedin.com/in/cindy-x-zhang/",
        resume: "https://cindyzhang977.github.io/cxz/static/media/resume.0903f5f7.pdf",
        website: "https://cindyzhang977.github.io/cxz/#/",
        blurb: "I have an unhealthy obsession with going to the beach. Whenever I get the chance, I enjoy spending my time outdoors and exploring new places, capturing picturesque views on my phone (this cost me a parking ticket once).",
        // repeat: '2',
    },
    {
        name: 'Joelle Siong Sin',
        img:  null,
        role: 'Social Director',
        email: 'jsiongsin@berkeley.edu',
        year: "Sophomore",
        committee: null,
        project: 'ClassifAI',
        tree: "Sami!",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/joellesiongsin/",
        resume: null,
        website: null,
        blurb: "Hi! I'm a sophomore studying EECS/IEOR! I love scenic runs, Trader Joe's flowers, and finding new songs for my Spotify playlists : )",
    },
    {
        name: 'Jun Hee Han',
        img:  null,
        role: 'Social Director',
        email: 'junheehan@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: "Seawarden",
        tree: "Emily Wang",
        leaf: "Ernest, Chanbin",
        linkedin: "https://www.linkedin.com/in/jun-hee-han-029527145/",
        resume: null,
        website: "https://instagram.com/junheehan",
        blurb: "talk to ethan chen and your life will change",
    },
    {
        name: 'Larissa Tsai',
        img:  null,
        role: 'Member Relations Director',
        email: 'lari.tsai@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: null,
        tree: "Vidya",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/larissatsai/",
        resume: null,
        website: null,
        blurb: "Hi! I'm Larissa, a CS major from Maryland. I love making Spotify playlists and buying boba/Sheng Kee to procrastinate. I'm currently learning amigurumi and making my way through various animes!",
    },
    {
        name: 'Maya Zheng',
        img:  null,
        role: 'Member Relations Director',
        year: "Sophomore",
        committee: null,
        project: "Find your zen",
        tree: "Ashley Chu",
        leaf: 'Danica Tang',
        linkedin: "https://www.linkedin.com/in/maya-zheng-15868b208 ",
        resume: null,
        website: null,
        blurb: "Movie nerd, bubble tea, matcha and roller coaster enthusiast. I'm also pretty interested in 3D graphics and animation. ",
    },
    {
        name: 'Ashley Chang',
        img:  null,
        role: 'Media Director',
        email: 'ashleychang@berkeley.edu',
        repeat: '4',
        year: 'Junior',
        committee: null,
        project: null,
        tree: 'Kamille',
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/ashchang/',
        resume: null,
        website: null,
        blurb: "hi! im ash and some things i love are music (lots of mandopop, kpop/krap, calm english(?)), asian dramas/anime, and pocket camp<3 i also enjoy cooking and running (sometimes)!",
    },
    {
        name: 'Erin Tsai',
        img:  null,
        role: 'Web Director',
        email: 'ertsai01@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: 'Vidhi',
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/erin-tsai-9b5a28167/',
        resume: null,
        website: 'https://ertsai01.github.io',
        blurb: "if i make web, does that make me a spider? sometimes i also dance and write music. also i love tea, hot cheetos, and animals (but only on video)",
    },
    {
        name: 'Ashley Eastman',
        img:  null,
        role: 'Industry Director',
        year: 'Junior',
        email: 'ashleyha@berkeley.edu',
        repeat: "3",
        committee: null,
        project: null,
        tree: "Jasmine Ang",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/ashleyeastman/",
        resume: null,
        website: null,
        blurb: "I love cooking for my friends, working out/doing handstands, and exploring the world! Fun fact: I know how to evacuate a full airplane in 90 seconds. A few favs~ Artist: Sam Cooke ~ Book: Les Miserables ~ Movie: Phantom of the Opera",
    },
    {
        name: 'Cynthia Lan',
        img:  null,
        role: 'Finance Director',
        year: "Sophomore",
        email: 'cynthialan@berkeley.edu',
        committee: "Social Committee",
        project: "Sea Warden, Build-A-Bear",
        tree: "Kristie",
        leaf: 'Euhan',
        linkedin: null,
        resume: null,
        website: null,
        blurb: "Hi I'm Cynthia! I like going to the beach, going on spontaneous adventures and grabbing food! ",
    },
]

export const projectLeaders = [
    {
        name: 'Angela Jiang',
        img:  null,
        role: 'Project Manager',
        email: 'ajjiang@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: 'Bridget Cheng',
        leaf: 'Tiffany Feng',
        linkedin: 'https://linkedin.com/in/angelajjiang',
        resume: null,
        website: null,
        repeat:1,
        blurb: "Hi I'm Angela! I'm a CS and Econ major from Kansas. I really like penguins and I also enjoy baking and dancing. ",
    },
    {
        name: 'Ethan Chen',
        img:  null,
        role: 'Project Manager',
        email: 'ethanyxchen@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: 'SeaWarden led by Jun Hee',
        tree: 'Matt Hashimoto!',
        leaf: 'Sebi Szafir',
        linkedin: 'https://www.linkedin.com/in/ethanchen23/',
        resume: "https://tinyurl.com/resumeEthanChen",
        website: 'https://www.joinavanti.com/',
        blurb: "I'm from and grew up in Hong Kong and I really like sports like soccer, basketball, tennis and F1! Codeology has given me so much, especially finding a community of friends as well as resources to help me in my CS career! ",
    },
    {
        name: 'Stephen Yang',
        img:  null,
        role: 'Project Manager',
        email: 'stephen.yang@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: "ClassifAI",
        tree: "Cindy",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/stephen-yang-/",
        resume: null,
        website: null,
        blurb: "ask me about the different ice cream places at berkeley",
    },
    {
        name: 'Ahmed Baqai',
        img:  null,
        role: 'Project Leader',
        email: 'abaq@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null, 
        tree: 'Haotian Ye',
        leaf: 'Lincoln Too', 
        linkedin: 'https://www.linkedin.com/in/ahmedbaqai/', 
        resume: 'https://ahmedbaqai.com/resume.pdf', 
        website: 'https://ahmedbaqai.com/',
        blurb: "Hey! I'm Ahmed. You probably know that tho cause you can see my name! Does it make me cool for pointing that out? No. I love snowboarding btw!",
    },
    {
        name: 'Chanbin Park',
        img: null,
        role: 'Project Leader',
        email: 'chanbin.park@berkeley.edu',
        year: 'Freshman',
        committee: null,
        project: null,
        tree: 'Jun Hee Han',
        leaf: null,
        linkedin: "https://www.linkedin.com/in/chanbin-park-4b795920b/",
        resume: null,
        website: "https://chanbinpark.com/",
        blurb: "I don't like avocados cuz they're too mushy. Can we change our mascot?",
    },
    {
        name: 'Eric Berndt',
        img:  null,
        role: 'Project Leader',
        email: 'ekberndt@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: 'ClassifAI',
        tree: 'Ali Matsumoto',
        repeat:'2',
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/ekberndt/',
        resume: null,
        website: null,
        blurb: "I love asking questions and learning new things :D",
    },
    {
        name: 'Ernest Goh',
        img:  null,
        role: 'Project Leader',
        email: 'ernest.goh20@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: null,
        tree: 'Jun Hee Han',
        leaf: 'Mizuho Li',
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Euhan Kim',
        img:  null,
        role: 'Project Leader',
        email: 'euhan123@berkeley.edu',
        year: 'Freshman',
        committee: null,
        project: null,
        tree: 'Cynthia Lan',
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/euhan-kim/',
        resume: null,
        website: null,
        blurb: "Hi, I'm Euhan! Play league with me :)) and gimme free food plz",
    },
    {
        name: 'Joelle Siong Sin',
        img:  null,
        role: 'Project Leader',
        email: 'jsiongsin@berkeley.edu',
        year: "Sophomore",
        committee: null,
        project: 'ClassifAI',
        tree: "Sami!",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/joellesiongsin/",
        resume: null,
        website: null,
        blurb: "Hi! I'm a sophomore studying EECS/IEOR! I love scenic runs, Trader Joe's flowers, and finding new songs for my Spotify playlists : )",
    },
    {
        name: 'Kevin Chow',
        img:  null,
        role: 'Project Leader',
        email: 'chowmein113@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: 'Beary hungry',
        tree: 'Trevor Baba',
        leaf: 'I’m a leaf',
        repeat:'2',
        linkedin: 'https://linkedin.com/in/kevin-chow-engineer/',
        resume: null,
        website: null,
        blurb: "Hi, I'm Kevin Chow and I am an EECS junior transfer from OC, CA. I like to hang with my codeology fam and friends, eat taco bell, play and listen to music, play video games, watch anime, etc. I just like to have fun so hmu and I'm likely to be down.",
    },
    {
        name: 'Maya Zheng',
        img:  null,
        role: 'Project Leader',
        year: "Sophomore",
        committee: null,
        project: "Find your zen",
        tree: "Ashley Chu",
        leaf: 'Danica Tang',
        linkedin: "https://www.linkedin.com/in/maya-zheng-15868b208 ",
        resume: null,
        website: null,
        blurb: "Movie nerd, bubble tea, matcha and roller coaster enthusiast. I'm also pretty interested in 3D graphics and animation. ",
    },
    {
        name: 'Pradeep Muthaiya',
        img:  null,
        role: 'Project Leader',
        year: 'Junior',
        committee: null,
        project: "Shares^2",
        tree: "Krishna, Shaylan, Kyle, Karthick, Sree, Vaib, etc.",
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "CS and Stats Sophomore from SoCal just vibing. Hmu if ur in LA and wanna grab food :)",
    },
    {
        name: 'Rachel Xin',
        img:  null,
        role: 'Project Leader',
        year: "Freshman",
        committee: null,
        email: "rachelxin@berkeley.edu",
        project: null,
        tree: 'David Lim',
        leaf: null,
        linkedin: "https://www.linkedin.com/in/rachelxin",
        resume: null,
        website: null,
        blurb: "Hello! I'm Rachel, and I am an EECS major from Orange County, CA. I enjoy playing tennis, baking/cooking, and trying new things during my free time.",
    },
    {
        name: 'Sadyant Behera',
        img:  null,
        email:'sadyant.behera@berkeley.edu',
        role: 'Project Leader',
        year: "Junior",
        committee: null,
        project: 'sea warden',
        tree: 'shaylan dias',
        leaf: null,
        linkedin: 'https://linkedin.com/in/sadyant',
        resume: null,
        website: 'https://GitHub.com/sadyant',
        blurb: 'i am huge.',
    },
    {
        name: 'Shaylan Dias',
        img:  null,
        role: 'Project Leader',
        email: 'shaylandias@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: 'Shares^2',
        tree: 'Kyle Hua',
        leaf: 'Krishna Ravi, Sady Behera',
        linkedin: 'https://linkedin.com/in/shaylan-dias/',
        resume: 'https://drive.google.com/file/d/18bhSmX8ZJpiR0C2ecscp3rjGO5reg1qU/view',
        website: 'https://shaylanmdias.com',
        blurb: "Hi! I'm Shaylan, I'm an EECS major who loves swimming, backpacking and lifting! I'm also a gaming/marvel/fantasy nerd lol",
    },
]

const a = [
    {
        name: 'Avocodeology',
        img: null,
        role: 'Mascot',
        year: '??',
        email: 'info@codeology.club',
        linkedin: 'https://www.linkedin.com/company/berkeley-codeology/mycompany/',
        tree: 'Persea americana',
        blurb: 'I like guac, Codeology, and being cute! I can be seen tabling with Codeology members — feel free to come by, say hi, and give me a pat <3'
    },
    {
        name: 'Ada Hu',
        img:  null,
        role: 'Active Member',
        year: 'Senior',
        email: 'adahu@berkeley.edu',
        committee: null,
        project: "Avanti",
        tree: "Jennifer Xiao",
        leaf: "Ashley Chu",
        linkedin: null,
        resume: null,
        website: "https://ada-hu.github.io/",
        blurb: "Hi hehe I'm a senior pls talk to me im bored",
    },
    {
        name: 'Alan Liu',
        img:  null,
        role: 'Active Member',
        email: 'alanliu2345@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: 'Build A Bear',
        tree: 'me',
        leaf: 'Kevin Nguyen',
        linkedin: 'https://www.linkedin.com/in/alan-liu-20/',
        resume: null,
        website: null,
        blurb: 'I like kbbq and boba, will beat you in smash, and listen to a lot of edm/hip hop',
    }, 
    {
        name: 'Amogh Maganahalli',
        img:  null,
        role: 'Active Member',
        email: 'amoghm2@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: "Avanti",
        tree: "Varun Murthy",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/amogh-maganahalli-4856a31a8/",
        resume: null,
        website: "https://www.instagram.com/amoghmaganahalli_/",
        blurb: "Yo! I'm a sophomore but this is still my first year in Berkeley! I really enjoy watching different kinds of shows (particularly sci-fi and comedy), playing video games, playing/following sports, and listening to music. If you wanna explore Berkeley or even just chill and talk or walk around, feel free to hmu! ",
    },
    {
        name: 'Annie Xu',
        img:  null,
        role: 'Active Member',
        email: 'annie.xu2025@berkeley.edu',
        year: 'Freshman',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "hi! i like volleyball, napping, sushi, and going on adventures",
    },
    {
        name: 'Angel Mau',
        img:  null,
        role: 'Active Member',
        year: 'Freshman',
        email: 'angelmau@berkeley.edu',
        linkedin: "www.linkedin.com/in/angelmau",
        tree: null,
        leaf: null,
        committee: null,
        project: null,
        resume: null,
        website: null,
        blurb: "I like lifting, console gaming and eating! ",
    },
    {
        name: 'Ashley Chu',
        img:  null,
        role: 'Active Member',
        email: 'ashchu@berkeley.edu',
        repeat: '2',
        year: 'Junior',
        committee: 'Website',
        project: null,
        tree: 'Ada',
        leaf: 'Maya',
        linkedin: 'https://linkedin.com/in/ashley-chu',
        resume: null,
        website: 'https://ashchu.github.io/',
        blurb: "hi! :^) i like egg tarts and movies. as you can see the name ashley is >>>",
    },
    {
        name: 'Charles Ming',
        img:  null,
        role: 'Active Member',
        year: 'Sophomore',
        email: 'charlesming@berkeley.edu',
        linkedin: "https://www.linkedin.com/in/charlesming/",
        tree: null,
        leaf: null,
        committee: null,
        project: null,
        resume: null,
        website: null,
        blurb: "i like playing chess + poker, making no progress at rsf, reading, and trying weird foods",
    },
    {
        name: 'Chetan Khanna',
        img: null,
        role: 'Active Member',
        email: 'chetan.khanna@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Danica Tang',
        img:  null,
        role: 'Active Member',
        email: 'danicat@berkeley.edu',
        year: 'Freshman',
        committee: null,
        project: null,
        tree: 'Maya Zheng',
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/danica-t/',
        resume: null,
        website: null,
        blurb: 'Hi! I’m Danica and I love to make crafts, play musical instruments, and bake! <3',
    },
    {
        name: 'David Lim',
        img:  null,
        role: 'Active Member',
        repeat: '2',
        email: 'david.lim@berkeley.edu',
        year: 'Sophomore',
        committee: "Media",
        project:  "Sea Warden",
        tree: "Satiya Kem",
        leaf: 'Rachel Xin',
        linkedin: "https://www.linkedin.com/in/davidlim7391/",
        resume: null,
        website: "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstleyVEVO",
        blurb: "yup yip yep yap yop",
    }, 
    {
        name: 'Dhruv Ganesh',
        img:  null,
        role: 'Active Member',
        email: 'dganesh@berkeley.edu',
        year: 'Freshman',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "If u mention Taco Bell plots I’m already down",
    },
    {
        name: 'Grace Altree',
        img:  null,
        role: 'Active Member',
        email: 'gracealtree@berkeley.edu',
        year: "Senior",
        committee: null,
        project: null,
        tree: "Srishti Goswamy",
        leaf: "Sami Oh",
        linkedin: "https://www.linkedin.com/in/grace-altree/",
        resume: null,
        website: null,
        blurb: "Here are some of my favorite ways to procrastinate coding: dancing, trying a new restaurant, playing banana grams, going to the beach, reading, sleeping... the list goes on.   ",
    },
    {
        name: 'Grace Juan',
        img:  null,
        role: 'Active Member',
        year: 'Freshman',
        email: "grace.wj@berkeley.edu",
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null, 
        resume: null,
        website: null,
        repeat: '2',
        blurb: "Hey, I'm Grace! I'm a freshman intending to major in computer science. I like tennis, piano, art, games, and music.",
    },
    {
        name: 'Jada Klein',
        img:  null,
        role: 'Active Member',
        email: 'jadaklein03@gmail.com',
        year: 'Freshman',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: "https://www.linkedin.com/in/jada-klein/",
        resume: null,
        website: null,
        blurb: "Heyo -- I'm a freshman studying CS. I like outdoor adventures, chill music, and yummy food :)",
    },
    {
        name: 'Jasmine Ang',
        img:  null,
        role: 'Active Member',
        year: 'Junior',
        email: 'jasmineang@berkeley.edu',
        committee: 'Social',
        project: null,
        tree: 'Jasper',
        leaf: 'Ashley Eastman',
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Justin Xu',
        img:  null,
        role: 'Active Member',
        year: 'Freshman',
        email: "justinxu@berkeley.edu",
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/justin-xu-556b6521b/', 
        resume: null,
        website: null,
        blurb: "hi! i love meeting people, trying new things, fruit, sports and not writing bios.",
    },
    {
        name: 'Kerrine Tai',
        img:  null,
        role: 'Active Member',
        email: 'kerrine@berkeley.edu',
        year: 'Freshman',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "Hi I'm Kerrine! I like plants and my hamster Potato :)",
    },
    {
        name: 'Kevin Nguyen',
        img:  null,
        role: 'Active Member',
        email: 'kevintnguyen@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: null,
        tree: 'Alan Liu',
        leaf: 'me',
        repeat: '3',
        linkedin: null,
        resume: 'https://docs.google.com/document/d/1QmpOYvcoc0Zip6e4xcVLJnarIIm8BdyE42IO-DY9KUU/edit',
        website: 'https://kevintngooyen.github.io/website/#/',
        blurb: "I am your typical Kevin Nguyen. I am from San Jose, like EDM, drive a Lexus, and play video games. ",
    },
    {
        name: 'Krishna Ravi',
        img:  null,
        role: 'Active Member',
        year: 'Senior',
        email: 'krishnaravi@berkeley.edu',
        committee: null,
        project: null,
        tree: "Shaylan Dias",
        leaf: "Pradeep Muthaiya",
        linkedin: "https://www.linkedin.com/in/krishna-ravi99/",
        resume: null,
        website: null,
        blurb: "Hi! I am a senior studying EECS and Data Science. Catch me @ first floor Moffitt getting absolutely nothing done.",
    },
    {
        name: 'Kristie Lin',
        img:  null,
        role: 'Active Member',
        year: 'Senior',
        email: 'kristielin13@berkeley.edu',
        committee: 'Social',
        project: null,
        tree: 'Alma',
        leaf: 'Cynthia Lan',
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Kyle Hua',
        img:  null,
        role: 'Active Member',
        email: 'kylehuuuaaa@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Kylie Ren',
        img:  null,
        role: 'Active Member',
        email: 'kxyr@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "Hi! I like going on photoshoots, playing valorant, studying plants/animals and making arts & crafts (or anything aesthetic lol)! ",
    },
    {
        name: 'Laura Pei',
        img:  null,
        role: 'Active Member',
        email: 'laur@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: "https://www.linkedin.com/in/laurapei/",
        resume: null,
        website: "https://lauraspberry.github.io/",
        blurb: "hello! I'm a second year EECS major from the Los Angeles area, and I love gudetama, good food, and sleeping for more than 9 hours <3",
    },
    {
        name: 'Lauren Zheng',
        img:  null,
        role: 'Active Member',
        email: 'laurenz@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: 'Build-a-bear',
        tree: 'Daniel Tseng',
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/lauren-zheng-2606',
        resume: null,
        website: null,
        blurb: "I love plushies, guitars, kdramas, and tea. ",
    },
    {
        name: 'Lincoln Too',
        img:  null,
        role: 'Active Member',
        email: 'lincoln99@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: 'ClassifAI',
        tree: 'Ahmed',
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "I like anime, sports, and board games. HMU!",
    },
    {
        name: 'Mallika Parulekar',
        img:  null,
        role: 'Active Member',
        email: 'mallika.parulekar@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: "Sea Warden",
        tree: "Aarushi",
        leaf: 'Ramya Chitturi',
        linkedin: "https://www.linkedin.com/in/mallikaparulekar/",
        resume: 'https://drive.google.com/file/d/1JF8Vr_nSIWZkEu12A21TLXBcvM4YatlS/view?usp=sharing',
        website: null,
        blurb: "Hi! I'm Mallika - a sophomore studying computer science who's also interested in math, economics and the law. When I'm not drinking boba and playing tennis, you can find me building things, trying my hand at fullstack and being a human learning about machine learning :)",
    },
    {
        name: 'Michael Zhang',
        img:  null,
        role: 'Active Member',
        year: 'Sophomore',
        email: 'zhang.michael@berkeley.edu',
        linkedin: null,
        tree: null,
        leaf: null,
        committee: null,
        project: null,
        resume: null,
        website: null,
        repeat: '2',
        blurb: "coffee, frank, n friends !!! say hi :)",
    },
    {
        name: 'Mizuho Li',
        img:  null,
        email:'limizuho@berkeley.edu',
        role: 'Active Member',
        year: "Freshman",
        committee: null,
        project: "Build a Bear",
        tree: "Ernest Goh",
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "Hi I’m Mizuho! I love  playing any random sports and a BIG fan of k drama. ",
    },  
    {
        name: 'Oliver Carmont',
        img:  null,
        role: 'Active Member',
        email: 'ocarmont@berkeley.edu',
        year: 'Freshman',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "Heyy! I'm a freshman from Spain, who loves playing soccer, running and binging on cheez-its.",
    },
    {
        name: 'Pradyun Kumar',
        img:  null,
        role: 'Active Member',
        email: 'pradyunkumar@berkeley.edu',
        year: 'Freshman',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "hi I like guacomole and anime and Kpop and listening to piano while I study",
    },
    {
        name: 'Ramya Chitturi',
        img:  null,
        role: 'Active Member',
        year: "Freshman",
        committee: null,
        email: "ramya.chitturi@berkeley.edu",
        project: null,
        tree: 'Mallika',
        leaf: null,
        linkedin: "https://www.linkedin.com/in/ramya-s-chitturi/",
        resume: null,
        website: null,
        blurb: "I love museums, sci-fi, and crosswords!",
    },
    {
        name: 'Shannon Or',
        img:  null,
        role: 'Active Member',
        year: "Sophomore",
        email:"shannonor@berkeley.edu",
        committee: null,
        project: "beary hungry",
        tree: 'Kyle Hua',
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "i love to eat, play basketball and try new things ",
    },
    {
        name: 'Tavleen Bhatia',
        img:  null,
        role: 'Active Member',
        year: 'Sophomore',
        email: 'tavleenbhatia@berkeley.edu',
        linkedin: "https://www.linkedin.com/in/tavleen-bhatia-498491217/",
        tree: null,
        leaf: null,
        committee: null,
        project: null,
        resume: null,
        website: null,
        blurb: "Heyo! I'm a sophomore studying MCB and Data Science. I love working out, trying out new recipes, dreaming of owning a pet cat, and lying on the glade in the sun :)) Hmu to obsess over Grey's Anatomy or share Spotify playlists!",
    },
    {
        name: 'Tiffanie Chau',
        img:  null,
        role: 'Active Member',
        email: 'tiffaniechau@berkeley.edu',
        year: 'Sophomore',
        committee: null,
        project: "Beary Hungry",
        tree: "ONLY THE BEST: AMY HUANG",
        leaf: "not ready to be a mother yet...",
        linkedin: "https://www.linkedin.com/in/tiffanielchau/",
        resume: null,
        website: null,
        blurb: "I'm a simple girl; there are three things I love: good food, opening packages, and being around awesome people. Codeology fulfills 2 out of those three things which makes me very happy. :) I'm interested in exploring the tech industry while deciding what to do with my life in college. ",
    },
    {
        name: 'Tiffany Feng',
        img: null,
        email:"tiffanylinyifeng@berkeley.edu",
        role: 'Active Member',
        repeat: '2',
        year: 'Junior',
        committee: null,
        project: 'Beary-Hungry',
        tree: "Angela Jiang",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/tiffanylinyifeng",
        resume: null,
        website: null,
        blurb: "Hi! I'm Tiffany, and I'm a Junior studying Computer Science and Business. I'm from San Diego, and I love being outdoors, baking, and traveling :)",
    },
    {
        name: 'Tommy Hang',
        img:  null,
        role: 'Active Member',
        year: 'Freshman',
        email: 'tommyhang@berkeley.edu',
        linkedin: "https://www.linkedin.com/in/tommy-hang-69a433212/",
        tree: null,
        leaf: null,
        committee: null,
        project: null,
        resume: null,
        website: "https://www.instagram.com/imatomster/",
        blurb: "THATS CRAZY! If you ever want to eat at Crossroads, I'll always eat with you. I love music, fencing, basketball, other stuff, and you <3",
    },
    {
        name: 'Vaibhav Gattani',
        img:  null,
        role: 'Active Member',
        email: 'vaibg@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: null,
        leaf: 'Vidhi Chander',
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Varun Murthy',
        img:  null,
        role: 'Active Member',
        year: 'Senior',
        committee: null,
        project: null,
        tree: "none",
        leaf: "Amogh",
        linkedin: "https://www.linkedin.com/in/varun-r-murthy/",
        resume: null,
        website: null,
        blurb: "I've been in Codeology since my second semester. Alongside EECS, I'm also doing a music minor!",
    },
    {
        name: 'Victor Zhou',
        img:  null,
        role: 'Active Member',
        year: 'Sophomore',
        email: 'shuaivzhou@berkeley.edu',
        linkedin: null,
        tree: null,
        leaf: null,
        committee: null,
        project: null,
        resume: null,
        website: null,
        blurb: "My left thumb's fingerprint duplicated itself ooga booga",
    },
    {
        name: 'Victoria Nguyen',
        img:  null,
        role: 'Active Member',
        year: 'Freshman',
        email: 'victoriahnguyen@berkeley.edu',
        committee: null,
        project: null,
        resume: null,
        tree: null,
        leaf: null,
        website: null,
        blurb: 'lover of Minecraft, milk, and mushrooms <33',
    },
    {
        name: 'Vidya Ganga',
        img:  null,
        role: 'Active Member',
        year: 'Junior',
        email: 'sreevidyaganga0@berkeley.edu',
        committee: null,
        project: null,
        tree: 'karthick but hes gone',
        leaf: 'larissa',
        linkedin: 'https://www.linkedin.com/in/sreevidya-ganga-70113076/',
        resume: null,
        website: null,
        blurb: 'i like oatmeal and warm hugs <3',
    },
 ];

function compare(a, b) {
    const nameA = a.name.toUpperCase();
    const nameB = b.name.toUpperCase();

    let comparison = 0;
    if (nameA > nameB) {
        comparison = 1;
    } else if (nameA < nameB) {
        comparison = -1;
    }
    return comparison;
}

const insertImg = (persons) => {
    for(let i = 0; i < persons.length; i++) {
        var obj = persons[i];
        const first = obj.name.split(" ")[0].toLowerCase() + (obj.hasOwnProperty('repeat') ? obj.repeat : '')
        try {
            obj.img = require('../images/members/' + first + '.jpg');
        } catch {
            obj.img = require('../images/members/default.jpg');
        }
    }
}

export const actives = a.slice(0, 1).concat(a.slice(1).sort(compare)); // sort everything after avocodeology!
insertImg(leadership);
insertImg(projectLeaders);
insertImg(a);

// saving bios from people who haven't graduated/quit but aren't in member database :'(
/*
{
        name: 'Amy Huang',
        img:  null,
        role: 'Web Director',
        year: 'Junior',
        committee: 'Web!',
        email: 'amyxjhuang@berkeley.edu',
        project: null,
        tree: 'Anna',
        leaf: 'Tiffanie <3 :3',
        linkedin: 'https://www.linkedin.com/in/amyxjhuang/',
        resume: 'https://tinyurl.com/amyhuangresume',
        website: 'https://amyhuang.web.app',
        blurb: 'I love tasty pot, smoothie, hot cheeto puffs, animal crossing, moffitt 1st floor!!! ',
    },
    {
        name: 'Sami Oh',
        img:  null,
        role: 'Project Leader',
        email: 'haotiany@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: 'Build-A-Bear',
        tree: "Grace Altree",
        leaf: null,
        linkedin: "https://www.linkedin.com/in/samantha-oh-3315b31b7/",
        resume: null,
        website: null,
        blurb: "I'm a junior interested in web design and development! I love cats, painting, and sitting in the sun :)",
    },
    {
        name: 'Kamille Dyan Fernando',
        img:  null,
        role: 'Project Leader',
        year: 'Junior',
        email: 'kamillef@berkeley.edu',
        committee: null,
        project: null,
        tree: 'Tiffany',
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Trevor Baba',
        img:  null,
        role: 'Project Leader',
        email:'trevor.baba@berkeley.edu',
        year: 'Junior',
        committee: null,
        project: "Pro-Bono",
        tree: 'Sherman',
        leaf: null,
        linkedin: 'https://www.linkedin.com/in/trevor-baba-000/',
        resume: null,
        website: null,
        blurb: 'I love playing basketball and collecting NFTs.',
    },
    {
        name: 'CJ Manna',
        img:  null,
        role: 'Active Member',
        year: 'Senior',
        email: 'charlesmanna@berkeley.edu',
        committee: null,
        project: null,
        tree: 'Micah',
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: "Talk to me about hiking, movies, and ethical design!",
    },
    {
        name: 'Dustin Luong',
        img:  null,
        role: 'Active Member',
        email: 'dstn.luong@berkeley.edu',
        year: 'Senior',
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
    {
        name: 'Satiya Kem',
        img:  null,
        role: 'Active Member',
        year: "Senior",
        committee: null,
        project: null,
        tree: null,
        leaf: null,
        linkedin: null,
        resume: null,
        website: null,
        blurb: null,
    },
*/
